platform :ios, ‘8.0’
use_frameworks!

target ‘MSReadhub’ do
    pod 'Alamofire', '~> 4.4'
    pod 'HandyJSON', '~> 1.7.1'
    pod 'ESPullToRefresh', '~> 2.6'
    pod 'SnapKit', '~> 3.2.0'
    pod 'SwiftDate', '~> 4.1.2'
    
    target 'MSReadhubTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'MSReadhubUITests' do
        inherit! :search_paths
        # Pods for testing
    end
end
